### PR TITLE
Splitbutton branch

### PR DESCRIPTION
**Pull request by Patrick1701**
Hi Sebastien,
may I introduce youuu...... theeeeeee SplitButton.

I hope it will pass your review. :-)

best regards
Patrick

### CODE REVIEW

**Comment by sebfz1** [comment]
Hi Patrick;

Thank you very much, I am looking at this asap!

Best regards,
Sebastien

**Comment by sebfz1** [comment]
> may I introduce youuu...... theeeeeee SplitButton.

Here comes the review! [tadaaaaa] :)

Patrick, let me tell you I really liked the way you implemented this! So I did not changed the logic you put in place, I have changed one or two things however:

1. IMO, a split button is still a button and should then behave like that (submitting a form typically). I've replaced the AjaxLink by an AjaxSubmitLink, added #onSubmit & #onError, and added #setDefaultFormProcessing to bypass form validation and update.
2. Selecting an action in the menu should not trigger this action (still IMHO), it selects the action available for the main button. I can be wrong and this is opened to discussion...
3. There was a small display issue while re-adding the button (the buttonset behavior was not reapplied). I've corrected this.
4. I have renamed SplitButton to SplitAjaxButton (because of the Ajax[Submit]Link), added the SplitButton (based on a SubmitLink). Both now extend AbstractSplitButton
5. I've refactored "a little bit", so don't be afraid if you look back at the code. However, the logic you put in place is absolutely maintained.
6. I've added 2 sample pages (for SplitButton & AjaxSplitButton)

As the result I think we have a new nice component! Well done Patrick and thanks again!

Best regards,
Sebastien

**Comment by Patrick1701** [comment]
Hi Sebastien,
> Patrick, let me tell you I really liked the way you implemented this!

Thanx for your positive feedback!

> 1\. IMO, a split button is still a button and should then behave like that

Ok, means, internal we just have a method named onSubmit() instead of onClick()?


> 2\. Selecting an action in the menu should not trigger this action (still IMHO)

I admit, I did not question that... I followed the example on JQuery
http://jqueryui.com/button/#splitbutton

On clicking the button an alert 'Running the last action' occured, so my conclusion was, the action must already be executed before. But I did not check the example if it really happens.

But I thought about this... and it becomes "my" main reason implementing it this way.
The example also shows a menu like entry "open..." (containing ellipsis ...), so usually in UIs this indicates, there must immediatly happen something... so I delegated the action.
As client developer your menu-entry implementation "can decide", if some further action should happen or not. That was the idea behind that.

> 3\. There was a small display issue

Ah, thanx.

Ok, on your next release I will try to change our internal implementation to yours and check if it is still working for us as expected.

best regards :-)
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

> Ok, means, internal we just have a method named onSubmit() instead of onClick()?

Yes, but also that is submits the form (by default)

> As client developer your menu-entry implementation "can decide", if some further action should happen or not. That was the idea behind that.

The problem is that menu-items are not form submitter, and the user cannot just decide to propagate to the SplitButton#onSubmit. Having a FormSubmitMenuItem could be one option. The other would be that I provide a flag property that handle this propagation (false by default?). But I should look at this in detail to see what's the most convenient...

Best regards,
Sebastien

**Comment by Patrick1701** [comment]
Good morning,

> Yes, but also that is submits the form (by default)

But it still works without any form?

> The problem is that menu-items are not form submitter

Ok, hmm... understand. I think, I would provide a boolean flag.
We use the split-button more like a menu. Any click of an item triggers the action. Clicking the button after a menu item was clicked once, the button itself just re-triggers the last action.

For us its a kind of click optimization on our ui for the user. Not to have a "choose first, click manually"-situation.

But, I agree, choosing an action first, and manually trigger it, by clicking the button, is also a valid and usable use-case for the split-button.

Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

> But it still works without any form?

Yes, [Ajax]SubmitLink are not mandatory to be attached to a form.

I tried to enhance to SplitButton yesterday evening but I did not found a nice/suitable solution to handle all these features, need to retry with a fresh new brain...

Best regards,
Sebastien.

**Comment by sebfz1** [comment]
Hi Patrick,

I didn't have time to work on this this week (you know what the week at work before vacation may look like...).
Anyway, I released `6.19.1`. If you would like to give it a try and let me know if it is convenient or not...

Thanks & talk to you soon,
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
I know its been a while... :-D

Today I had a try to migrate to your SplitButton impl, but I'm not able to set a ```IMenuItem``` as default-model-object.

You've changed the GenericPanel from ```GenericPanel<IMenuItem>``` to ```GenericPanel<List<IMenuItem>>```.

And your inner button holds the model-object of the selected ```IMenuItem```.
I'm not able to reach and set it.

So, I would suggest, holding the list as member, and change the model-object of the generic panel to the current selected ```IMenuItem```.

This is also nearer to the handling of model-objects like e.g. ```DropDownChoice```s.

But this could lead into API breaks for others...
Sorry for the very late feedback.

best regards
Patrick

**Comment by Patrick1701** [comment]
Concerning the API break... do you think anyone ever asks the SplitButton for its getModelObject() returning the list of IMenuItems?

**Comment by Patrick1701** [comment]
Hi Sebastien,
did you notice my last two comments?

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Thanks for the recall, I often forget when issue is closed... (but as it is a PR, no way to reopen it)
I think I remembered to agree with your statement, I will try to process asap...

Thanks & best regards,
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
any news here?

Should I open an new issue, to have that as official feature request?

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick, so sorry!  I forgot once again... :( 
And of course... I'm on vacation this week :)

**Pull request merged**
