### PR TITLE
Wicket8.10.2

### PR DESCRIPTION
**Pull request by Patrick1701**
Hi Sebastien,
due to ticket #334 and #336 I created an own release-branch wicket8.10.2.

Could you please create a final release 8.10.2 from this branch and deploy it to maven central?

best regards
Patrick
P.s. not sure, if PR target (wicket8.x) is the correct one. Get in contact, if I need to change something.

### CODE REVIEW

**Comment by sebfz1** [comment]
Hi Patrick,

It's not easy to understand what you trying to do...

Is this something that is fixed but need to be backported to another version? 
For instance you want to start from `8.10.1` and add one or two commits from after this version to generate `8.10.2`? 
If so, you cannot create a MR to wicket8.x branch. Instead checkout from the commit/version you want to start. You will be in detached head so create a new branch, cherry-pick the commits you want (record the sha1 beforehand) and push your branch. Now, since that branch does not exists here, you cannot create a MR (there is nowhere to merge to). Instead tell me where your branch is and I will get it. 
And if I am all wrong... Please explain/remind me what you want :)

**Comment by Patrick1701** [comment]
Hi Sebastien,

> Is this something that is fixed but need to be backported to another version?

Yes.


> For instance you want to start from 8.10.1 and add one or two commits from after this version to generate 8.10.2?

Yes.


> If so, you cannot create a MR ...

What is an MR? Merge Request?


> You will be in detached head so create a new branch, cherry-pick the commits you want...

I did something similar. I branched the 8.10.1 (afad54aedd3de51c79ace519a66959b03850201c) to 8.10.2 on my own fork of your repository and cherry-picked two commits.


> Instead tell me where your branch is and I will get it.

https://github.com/Patrick1701/wicket-jquery-ui/tree/wicket8.10.2
Having cherry-picked commits 652ab8ca2c2ff1e121ec3bf6016baa57c5d2bac0 and 02c4b40d2655b3f3bfde5ac23b633df7f79f2f5e on top of afad54aedd3de51c79ace519a66959b03850201c.

Hope this helps? :-)
Patrick

**Comment by sebfz1** [comment]
Ok perfect, that should work. I will look at it asap.
Yes MR is Merge Request, but it's Gitlab vocabulary, my bad :D

**Comment by Patrick1701** [comment]
@sebfz1 Hi Sebastien, any news here? Thanx Patrick

**Comment by sebfz1** [comment]
Yes, built the branch, and plan the release for tomorrow (it's bank holiday
here). Didn't had enough time last weekend...

**Comment by sebfz1** [comment]
Hi Patrick, `8.10.2` is on its way to Maven Central....

**Pull request closed without merging**
