### PR TITLE
Issue #353: Upgrade to Wicket 10

### PR DESCRIPTION
**Pull request by reckart**
- Set version to 10.0.0-SNAPSHOT
- Update Wicket to 10.0.0-M1-SNAPSHOT
- Update maven-war-plugin to enable builds on Java 19

Best create a wicket10.x branch and re-target this PR.

### CODE REVIEW

**Comment by reckart** [comment]
@sebfz1 I've done successful initial tests with building my application against this PR and against the 10-xxx-SNAPSHOT versions of  Wicket, Wicket Boostrap, Wicket Spring Boot, etc. I think it might be a good start to merge the PR as-is into a new `wicket10.x` branch there is also a workable "official" branch for the migration to Wicket 10 in your project?

**Comment by sebfz1** [comment]
Thank you very much for this Richard, I'll try to take care of it today or
tomorrow!

**Comment by sebfz1** [comment]
Hi Richard, I've created `wicket10.x` branch with 097914d0c. Thanks a lot!

**Comment by reckart** [comment]
Yay!!!!

**Pull request closed without merging**
