### PR TITLE
implemented JQueryUI Selectmenu; #214

### PR DESCRIPTION
**Pull request by Patrick1701**
Hi Sebastien,
I hope it will pass your QA. :-D

best regards
Patrick

### CODE REVIEW

**Comment by sebfz1** [comment]
Hi Patrick,

Looks very good to me! :)
Did you test with the renderer too?

Thanks & best regards,
Sebastien.

**Comment by Patrick1701** [comment]
"the renderer"  ?
Do you mean constructed with an IChoiceRencerer?
I had a test with one of my drop-down-choices with wickets EnumChoiceRender.

**Comment by sebfz1** [comment]
> Do you mean constructed with an IChoiceRencerer?

Yes, that's what I meant.

> I had a test with one of my drop-down-choices with wickets EnumChoiceRender.

Ok, should be good enough! I will try to find some time to make the sample pages...

**Comment by Patrick1701** [comment]
Ok, and I will prepare another branch, showing the problem mentioned in https://github.com/sebfz1/wicket-jquery-ui/issues/213#issuecomment-164791027

**Comment by Patrick1701** [comment]
>  I will try to find some time to make the sample pages...

Let me try... so I can get used to it...
Can I just re-create a pull request?

**Comment by sebfz1** [comment]
Thanks Patrick!

Basically, I think you can just copy/paste the kendo DDL samples in a `pages.dropdown` package
You need a `.text` file in the resource folder that match the `.java` files
The page titles are located in `SampleApplication.properties`
And the left menu in `TemplatePage.html`

As I did not merge yet, you can just push to the same branch, the PR will be updated accordingly.

Best regards,
Sebastien.

**Comment by sebfz1** [comment]
Hi Patrick,

I've deployed `6.21.1`
The changelog is the same than `7.2.0`, so please have a look:
https://github.com/sebfz1/wicket-jquery-ui/releases/tag/wicket-jquery-ui-7.2.0

Enjoy :)
Sebastien.

**Comment by Patrick1701** [comment]
Hi Sebastien,
thanx a lot.

Now, I pushed the samples... can you see them, or must I create a new pull request, because this one is closed?
(Sorry, being so late with the samples... I was ill the last 10days)

kind regards
Patrick

**Comment by sebfz1** [comment]
Hi Patrick,

Thanks a lot!
Yes, a PR would be fine...

Best regards & welcome back!
Sebastien

**Pull request merged**
