### PR TITLE
WICKET-6287 Switch from json.org to open-json - 8.x

### PR DESCRIPTION
**Pull request by bitstorm**
PR to replace the old json code

### CODE REVIEW

**Comment by sebfz1** [comment]
Thanks a million Andrea! :)

**Comment by sebfz1** [comment]
I supposed the build will pass when https://github.com/apache/wicket/pull/193 will be merged...

**Comment by bitstorm** [comment]
Yep! it's a chicken and egg situation :D. once Wicket is fine everything should pass...

**Comment by klopfdreh** [comment]
I also think this is the right way to go in future to move out the json classes, because we can manage fixes within this library even easier and you are also able to decide to exclude the open-json library and plug in any other implementation or to switch to json.org if you are fine with the license.

**Comment by martin-g** [comment]
> I also think this is the right way to go in future to move out the json classes, because we can manage fixes within this library even easier and you are also able to decide to exclude the open-json library and plug in any other implementation or to switch to json.org if you are fine with the license.

But they don't really share common API. I didn't spend much time on checking the diffs but from the discussions I've got the impression that it is not as easy as replacing a dependency.

**Comment by klopfdreh** [comment]
> But they don't really share common API. I didn't spend much time on checking the diffs but from the discussions I've got the impression that it is not as easy as replacing a dependency.

I think this is only for the first time, because there are some changes which were made in Apache Wicket that have to be integrated into open-json. (e.g. JSONFunction)

And as you can see in the 6.x / 7.x branch the only changes to ensure the API consistency was to override methods not provided by open-json at the current state and throw exceptions in this case.

But if the implementation drifting more to their own API you are right - it will not that easy to exchange the dependency.

**Comment by sebfz1** [comment]
Closing as overlapped by https://github.com/sebfz1/wicket-jquery-ui/pull/256

**Pull request closed without merging**
