### PR TITLE
Wicket jquery ui 6.19.2 BugFix branch / for adapted fix #199

### LINKED ISSUE #199: KendoUI DateTimePicker sometimes does not change its internal format when deactivating timepicker
Hi Sebastien,
I have a conversion bug here, but I'm not really sure, whats the core problem is.

It seems on deactivating the timepicker, on some circumstances internally it still uses date format 'hh.dd.yy HH:mm' instead of 'hh.dd.yy' (or other way around) and this leads into an conversion exception.

I created a quickstart, because I wasn't able to fix it.

Could you please have a look?

To reproduce it:
- enter the homepage
- change the allday checkbox
- click go
- change the allday checkbox
- click go
```
    Error while parsing datetime: date was '11.09.15' and time was '00:00'
    Error while parsing datetime: date was '11.09.15' and time was '00:00'
```

Otherway around (first change, the boolean Model to true, to let the timepicker be disabled on entering the page)

- then enter the homepage
- change the allday checkbox
- click go
- change the allday checkbox
- click go
```
    Error while parsing datetime: date was '11.09.15' and time was 'null'
    Error while parsing datetime: date was '11.09.15' and time was 'null'
```

https://www.dropbox.com/s/d7sdcal4togfzoo/AjaxDateTimePicker2.zip?dl=0

kind regards
Patrick

Update: had a bug... please make sure use AjaxDateTimePicker2.zip

### PR DESCRIPTION
**Pull request by Patrick1701**
Hi Sebastien,
I'm not sure, if I'm doing right, what I do here... but I need a bugfix version of 6.19.3 containing the fix #199.

I created a separate branch and adapted the fix, and I think its working.
Tested with my local scheduler implementation.

I don't want to release a local version, so could you please do a bugfix release 6.19.3?

thanx a lot and kind regards
Patrick

### CODE REVIEW

**Comment by sebfz1** [comment]
Hi Patrick,

Would `6.20.2` be fine for you? Or you really need `6.19.3`?

Thanks,
Sebastien.

**Comment by Patrick1701** [comment]
Unfortunately... need 6.19.3 and possibly will also need 6.20.2, if no 6.21.0 will arise the next weeks. My RM branched our master into test-branch, before I was able to upgrade to 6.20.0. Our policy says, "for external frameworks only bugfix version upgrades allowed for test branches".
6.19.3 would be nice to Tuesday. No need for today or weekend...
If not possible, I'm allowed to do a local release, but I thought to ask you first, because my RM don't like the idea having versioning of external framework in-house.

Patrick

**Comment by sebfz1** [comment]
Ok, will release `6.19.3` with the fix (this WE). You really are a VIP, Patrick!

**Comment by Patrick1701** [comment]
Thank you very much, Sebastien!

**Comment by sebfz1** [comment]
Released `6.19.3`, enjoy! :gift:

**Pull request closed without merging**
