### PR TITLE
Fixes #161 - Introduce GenericJQueryContainer and use it wherever #getMo...

### LINKED ISSUE #161: Make use of Wicket's IGenericComponent where applicable

### PR DESCRIPTION
**Pull request by martin-g**
...delObject() is needed

### CODE REVIEW

**Comment by martin-g** [comment]
@sebfz1 Is such change acceptable for 6.x branch? 
I know you have the freedom to break the APIs :-)
It is not something important to my project so I'm fine to apply it only to 7.x too.

**Comment by sebfz1** [comment]
Hi Martin,

Thank you very much for this!
That's an update I wanted to do since a long time... but I always have something else to do and I forgot!.. :)

If we introduce `GenericJQueryPanel`, we will have a naming issue, because if `GenericJQueryPanel` extends `GenericPanel`, it should be `JQueryGenericPanel` so we will have :
`JQueryGenericPanel`
`GenericJQueryContainer`
And it looks a little bit weird...

What about renaming `GenericJQueryContainer` to `JQueryGenericContainer`? (I think I would prefer...)

Best regards,
Sebastien.

**Comment by sebfz1** [comment]
Footnote: I if you are using wicket-jquery-ui -SNAPSHOT version (6.x or 7), be aware that you should also use wicket snapshot version in your project too, until the next release, due to WICKET-5889 (but only InputDialog & InputWindow are impacted)

**Comment by martin-g** [comment]
> What about renaming GenericJQueryContainer to JQueryGenericContainer?

Done.

Do you want me to add JQueryGenericPanel too?

**Comment by sebfz1** [comment]
If you don't mind, with pleasure :)
Also, we can apply the change in master (wicket6) branch too. Actually, I also prefer to keep both branches to be the most aligned as possible...

**Comment by martin-g** [comment]
Voila!

**Comment by sebfz1** [comment]
Thank you very much Martin, I will merge and take care of the rest afterwards (formatting, etc)

**Comment by martin-g** [comment]
I'll change my formatting settings to use Wicket's ones!

**Comment by sebfz1** [comment]
Actually I've some other settings that slightly differs.
https://github.com/sebfz1/wicket-jquery-ui/blob/master/eclipse-cleanup.xml
https://github.com/sebfz1/wicket-jquery-ui/blob/master/eclipse-formatter.xml

But if you use wicket settings (i know you are not using eclipse), that's
will be close enough :)

I am currently implementing changes to wicket7.x so please don't do it :)

Thanks & best regards,
Sebastien.

**Pull request merged**
