### PR TITLE
Update a version of moment.js to 2.19.3

### PR DESCRIPTION
**Pull request by kazukisan**
https://github.com/sebfz1/wicket-jquery-ui/issues/280

### CODE REVIEW

**Comment by sebfz1** [comment]
Hi, thanks for this!
@martin-g, would it be possible for you to merge this PR please? I'm in
vacation for still a week and I cannot do a lot until I return... Thanks a
lot in advance! :)

**Comment by martin-g** [comment]
Merged!
Should I make a release too ?

**Comment by kazukisan** [comment]
Thank you @martin-g , and I am personally voting yes because it will be really great to be able to pull this through internal firewall with security vulnerability no longer being flagged. (But I am not the main developer here so it is up to you of course).

**Comment by martin-g** [comment]
Which version do you use, @kazukisan ? 6.x/7.x/8.x ?
I guess I should cherry-pick this to all active branches.

**Comment by kazukisan** [comment]
In my particular case, it looks like 7.x (7.9.0 to be specific):
https://github.com/webanno/webanno/blob/master/pom.xml

But I think it makes sense to apply in all active branches, too.

**Comment by sebfz1** [comment]
The snapshot is automatically deployed, but if it is not enough it would be
great to perform a patch release, yes! :)

**Comment by sebfz1** [comment]
(only on master, wicket 7.x for now, i will perform the cherry pick and
release the other branches next week...)

**Comment by martin-g** [comment]
The deployment failed twice. 
First settings.xml had an old password.
Second failure due to connection drop.
Now there are tags for 7.9.1 and 7.9.2. I'm trying to remove them but Github says that I am not authenticated ...
@sebfz1 Should I release 7.9.3 or should I try harder to remove those two tags and release 7.9.1 ?

**Comment by sebfz1** [comment]
7.9.3 is fine, no worry

**Comment by martin-g** [comment]
I've managed to convince Github who I am!
Now I'm trying again with 7.9.1.

**Comment by martin-g** [comment]
It always fails with:

```
] [INFO] wicket-kendo-ui-theme-uniform ...................... SUCCESS [  6.904 s]
[INFO] [INFO] wicket-jquery-ui-samples ........................... FAILURE [09:20 min]
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 15:15 min
[INFO] [INFO] Finished at: 2017-12-05T12:08:34+02:00
[INFO] [INFO] Final Memory: 66M/776M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [WARNING] The requested profile "frontend" could not be activated because it does not exist.
[INFO] [ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.5:deploy (injected-nexus-deploy) on project wicket-jquery-ui-samples: Remote staging failed: java.net.SocketException: Connection reset -> [Help 1]
[INFO] [ERROR] 
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
```

**Comment by sebfz1** [comment]
The release process should work fine, with mvn release:prepare and mvn
release:perform. I don't know why you are experiencing those issues... :(

On Dec 5, 2017 13:10, "Martin Grigorov" <notifications@github.com> wrote:

It always fails with:

] [INFO] wicket-kendo-ui-theme-uniform ...................... SUCCESS
[  6.904 s]
[INFO] [INFO] wicket-jquery-ui-samples ...........................
FAILURE [09:20 min]
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 15:15 min
[INFO] [INFO] Finished at: 2017-12-05T12:08:34+02:00
[INFO] [INFO] Final Memory: 66M/776M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [WARNING] The requested profile "frontend" could not be
activated because it does not exist.
[INFO] [ERROR] Failed to execute goal
org.sonatype.plugins:nexus-staging-maven-plugin:1.6.5:deploy
(injected-nexus-deploy) on project wicket-jquery-ui-samples: Remote
staging failed: java.net.SocketException: Connection reset -> [Help 1]
[INFO] [ERROR]
[INFO] [ERROR] To see the full stack trace of the errors, re-run Maven
with the -e switch.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sebfz1/wicket-jquery-ui/pull/281#issuecomment-349257578>,
or mute the thread

**Comment by martin-g** [comment]
No idea.
It failed 4 times on deploying the samples.

Do you really want to deploy the samples (a .war file) to Maven ?
In the past I have excluded the examples projects from being deployed to Maven for Wicket, Wicket-Bootstrap and all WicketStuff projects to make the deployment less painful.

**Comment by sebfz1** [comment]
Actually the eviction has never worked. :( I always let it upload, and the
I suppress manually... If you can manage to not upload it, that would be
awesome!

**Comment by martin-g** [comment]
I've disabled (commented out) nexus-staging-maven-plugin and now the release process skips the deployment of the samples.
@kazukisan 7.9.1 is at Maven Central!
@sebfz1 Please review my commits and revert if you think that something is not correct!

**Comment by sebfz1** [comment]
Great, thanks a million Martin! Sorry it has caused so much pain! :-/
I will double check the changes next week!...

**Comment by kazukisan** [comment]
Thank you for the release! Huge thanks for getting to this very quickly!

I just received a report that wicket-jquery-ui-core was able to be fetched through nexus firewall in my organization's environment, using version 7.9.1. (And hopefully this change is good for all others, too)

**Pull request merged**
