### PR TITLE
Wysiwyg editor is updated to have latest dependencies, code clean-up

### PR DESCRIPTION
**Pull request by solomax**
I have updated plugin to have latest bootstrap and bootstrap-wysiwyg versions
Will appreciate if you can review the changes

### CODE REVIEW

**Comment by solomax** [comment]
Hello @sebfz1 can you also check this PR and merge it?

**Comment by sebfz1** [comment]
Sounds good, thanks a lot Maxim! (and Martin! ;) )

**Comment by solomax** [comment]
Thanks!
Previous version doesn't work well with jquery 3.2.1 :(

**Comment by sebfz1** [comment]
- [ ] cherry pick to master & wicket6.x

**Pull request merged**
