### PR TITLE
Allow using custom values as identifier for Sortable items

### PR DESCRIPTION
**Pull request by martin-g**
Change the type of SortableEvent#hash to String and move the casting to int in SortableBehavior#findItem()/Sortable#findItem().
This way a specialization of Sortable(Behavior) could use something else than the hashCode if needed.

### CODE REVIEW

**Comment by martin-g** [comment]
@sebfz1 What do you think about this change?
In my case the item is a JAXB generated class and has no override `#hashCode`. After deserialization the hashCode is the new object identity so it breaks.

**Comment by sebfz1** [comment]
Hi Martin,

I understand the concern... But what about HashListView#onBeginPopulateItem()?
It still uses hashCode...
https://github.com/sebfz1/wicket-jquery-ui/blob/3f7edbe64206de9a5dfbb607c5820addff6a1594/wicket-jquery-ui/src/main/java/com/googlecode/wicket/jquery/ui/interaction/sortable/Sortable.java#L340

So my question is: how #findItem helps you to retrieve items?

**Comment by martin-g** [comment]
I override both `#onBeginPopulateItem()` and `#findIem()` here.
Before this PR it is possible to encode custom value (i.e. override `#onBeginPopulateItem`) but it is not possible to decode it.

**Comment by sebfz1** [comment]
> I override (...) #onBeginPopulateItem()

Ha, I see! I though you did find a magical other way I didn't know! ;)

I completely agree about your change proposal... Thanks a lot!
I just need to think about 2 things:
- The code repetition in the two `#findItem()`. But hard to find a better way, which does not affect code readability...
- The fact that you renamed `hash` to `id`... I understand it's now not necessary a hash, but I have some concerns about 'id', because it could by an id, a uuid, a hash, a key... and I am afraid 'id' could be confusing, considering the used html data attr is named 'hash'... Not a big deal but it puzzles me :)

I will merge it asap... Thanks again!

**Comment by martin-g** [comment]
itemIdentifier?

**Comment by sebfz1** [comment]
Well yes, `itemId` could be good!.. :)
I will see how it looks when I will merge...

**Pull request merged**
