### PR TITLE
Fixes issue #308: single 'y' is patched in the pattern

### PR DESCRIPTION
**Pull request by solomax**

### CODE REVIEW

**Comment by sebfz1** [comment]
Thanks a lot, Maxim. I'm looking at this asap!

**Review by martin-g — COMMENTED** [review]
New unit test(s) would be nice!

**Comment by solomax** [comment]
Hello @martin-g,
There are no unit tests in this project
I can add one but I'm not sure how can I test changes in Kendo js library :(

**Comment by martin-g** [comment]
> There are no unit tests in this project

oh, right! I've forgotten this small detail :-)

**Review by martin-g — APPROVED** [review]

**Comment by sebfz1** [comment]
Thanks Martin and Maxim! :))

**Comment by solomax** [comment]
Thanks :)
Any chance to get this version released? :)

**Comment by sebfz1** [comment]
You're welcome, Maxim!
For wicket 9.x?

**Comment by solomax** [comment]
Hello @sebfz1 
Could you please release 9.0.0-M3? :))

**Comment by sebfz1** [comment]
Already done! :)
Didn't had time to make the announcement yet... I will release 7.x and 8.x
this weekend and then make the announcements...

**Comment by solomax** [comment]
Thanks a lot :)

**Pull request merged**
