### PR TITLE
fullcalendar is updated to latest 3.x version: 3.10.2

### PR DESCRIPTION
**Pull request by solomax**
Hello @sebfz1,

could you lease create SNAPSHOT with this version? :)

BTW latest version of fullcalendar is 5.7.2, new version has no dependencies to `jquery`, `jquery-ui` and `moment.js` shall I try to create PR with update to this version? or maybe you have time for this? :)

### CODE REVIEW

**Comment by solomax** [comment]
@sebfz1 ping :)

**Review by martin-g — APPROVED** [review]

**Comment by sebfz1** [comment]
Thanks! I'll do it tomorrow or Saturday! :)

**Comment by sebfz1** [comment]
Hi Maxim, deployed `9.3.2-SNAPSHOT`.
I tried removing the dependency to `moment.js` but it didn't worked. I'll try to investigate...
I you think it's good to be released, I will release `9.3.2`...

**Comment by solomax** [comment]
Thanks for the SNAPSHOT @sebfz1 !

weird enough this file https://github.com/sebfz1/wicket-jquery-ui/blob/wicket9.x/wicket-jquery-ui-calendar/src/main/resources/com/googlecode/wicket/jquery/ui/calendar/resource/fullcalendar.js still has old version :(

moment.js is not required since v4 https://fullcalendar.io/docs/v4/upgrading-from-v3

Both v4 and v5 introduces breaking changes
https://fullcalendar.io/docs/upgrading-from-v4

So I guess it worth to migrate to v5 directly ...

**Comment by sebfz1** [comment]
I deployed the snapshot from another branch from your commit. I will merge
as soon as you confirm it's working as expected....

**Comment by solomax** [comment]
everything works as expected, thanks! :)

**Pull request closed without merging**
